// Fitness Knowledge V2 — which exercise ids each SHIPPED knowledge version contained, so a run solved under an
// older version can tell "new to knowledge" apart from "excluded at the time" (lifecycle: a better plan may now be
// possible). Append a version here when exercises are added; never edit a shipped list.

export const KNOWLEDGE_EXERCISE_IDS: Record<string, readonly string[]> = {
  "0.4.0": [
    "exercise.assisted_pull_up",
    "exercise.back_extension",
    "exercise.band_assisted_pull_up",
    "exercise.band_pull_apart",
    "exercise.banded_lateral_walk",
    "exercise.barbell_back_squat",
    "exercise.barbell_bench_press",
    "exercise.barbell_row",
    "exercise.bodyweight_squat",
    "exercise.box_jump",
    "exercise.bulgarian_split_squat",
    "exercise.cable_chest_fly",
    "exercise.cable_crunch",
    "exercise.cable_curl",
    "exercise.cable_lateral_raise",
    "exercise.cable_pallof_press",
    "exercise.cable_triceps_pushdown",
    "exercise.cable_woodchop",
    "exercise.calf_raise",
    "exercise.chest_supported_row",
    "exercise.chin_up",
    "exercise.conventional_deadlift",
    "exercise.copenhagen_plank",
    "exercise.dead_bug",
    "exercise.dumbbell_bench_press",
    "exercise.dumbbell_bicep_curl",
    "exercise.dumbbell_lying_triceps_extension",
    "exercise.dumbbell_romanian_deadlift",
    "exercise.dumbbell_row",
    "exercise.dumbbell_shoulder_press",
    "exercise.dumbbell_split_squat",
    "exercise.dumbbell_step_up",
    "exercise.face_pull",
    "exercise.farmer_s_carry",
    "exercise.front_squat",
    "exercise.glute_bridge",
    "exercise.goblet_squat",
    "exercise.hack_squat",
    "exercise.hammer_curl",
    "exercise.hanging_knee_raise",
    "exercise.hip_abduction_machine",
    "exercise.hip_adduction_machine",
    "exercise.hip_thrust",
    "exercise.incline_dumbbell_press",
    "exercise.inverted_row",
    "exercise.kettlebell_suitcase_carry",
    "exercise.kettlebell_swing",
    "exercise.lat_pulldown",
    "exercise.lateral_raise",
    "exercise.leg_curl",
    "exercise.leg_extension",
    "exercise.leg_press",
    "exercise.machine_chest_press",
    "exercise.machine_shoulder_press",
    "exercise.nordic_hamstring_curl",
    "exercise.overhead_cable_triceps_extension",
    "exercise.overhead_press",
    "exercise.pike_push_up",
    "exercise.plank",
    "exercise.pull_up",
    "exercise.push_up",
    "exercise.reverse_dumbbell_fly",
    "exercise.reverse_lunge",
    "exercise.romanian_deadlift",
    "exercise.seated_cable_row",
    "exercise.seated_calf_raise",
    "exercise.side_plank",
    "exercise.single_leg_calf_raise",
    "exercise.single_leg_romanian_deadlift",
    "exercise.trap_bar_deadlift",
    "exercise.walking_lunge",
  ],
};

/** Whether an exercise existed in the given shipped knowledge version (unknown version → assume it did). */
export function existedIn(version: string, exerciseId: string): boolean {
  const ids = KNOWLEDGE_EXERCISE_IDS[version];
  return ids ? ids.includes(exerciseId) : true;
}
